import type { Metadata } from "next";
import { Lato } from "next/font/google"; 
import "./globals.css";
import PageTransition from "@/components/PageTransition";


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body>
        <PageTransition>{children}</PageTransition>                  
      </body>
    </html>
  );
}

const lato = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: "Fiança Rápida ",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${lato.variable} antialiased`}>
//         {children}
//       </body>
//     </html>
//   );
// }