import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import { Toaster } from "sonner"; 

const lato = Lato({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: "Fiança Rápida",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${lato.variable} antialiased`}>
        <Toaster richColors />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
